### ISSUE TITLE
Error when removing panes in checkout

### ISSUE THREAD

**Issue by cl83** [mitrpaka/commerce_klarna_checkout#1]
When using klarna checkout we don't want the user to enter the contact information manually before the Klarna iframe. We want to get all user data from Klarna.

This is the ideal workflow:
Cart -> Klarna checkout iframe -> Completion message 

After we disable all user-address related panes we cant checkout.

This is the error message:
Message | InvalidArgumentException: The $step_id cannot be empty. in Drupal\commerce_checkout\Plugin\Commerce\CheckoutFlow\CheckoutFlowBase->buildForm() (line 235 of /app/web/modules/contrib/commerce/modules/checkout/src/Plugin/Commerce/CheckoutFlow/CheckoutFlowBase.php).
-- | --

This is how the checkout flow is configured (D8):
https://www.evernote.com/shard/s59/sh/8e9462e2-28e6-43fd-ac84-f3ae67bf523b/85b23d06c3ff11bfc0b8e16398f38d4b

This is how it looks in the D7 module (our current setup):
https://www.evernote.com/shard/s59/sh/5f756fbb-edb5-4be4-8a3a-2ed4442df009/e0bc1315f5aa352d6d15fbd6dbbeb2fa

**Comment by mitrpaka** [comment]
In commerce 2.x each payment gateway that implements either on-site or off-site payment gateway needs to have Payment information pane included in the checkout flow (along with Payment process pane). If no Payment information pane included, there will not be any payment gateway selection done and as a result of that error message mentioned in the issue is raised.

To use default checkout flow provided by the commerce, minimum workflow is:
Cart -> Payment information -> Klarna checkout iframe -> Completion message 

https://www.evernote.com/shard/s646/sh/12c88331-9286-49a2-af47-35498f1ca8af/3ccd77740e523bd24d40a6f4fd6033d5

Issue with Payment information (with Klarna checkout) is that payment information includes billing information details that you would like to bypass. In the issue queue there is already ticket created to allow less detailed billing information collected ([#2820122](https://www.drupal.org/node/2820122)).

Meanwhile, if you want to bypass collecting billing information details, are as follows:
1) Create a custom checkout flow that replaces payment information pane with custom pane that provides selection of payment gateway (i.e. klarna checkout) and then either bypasses or sets billing profile in the code (without UI interaction).
2) Create "workaround" with hook_form_alter() in your custom module. Not best approach though but ... 

It will hide the payment information and set billing profile in the background with some default value. Setting "Update billing profile using information from Klarna" to Yes will cause billing profile overridden at the time of push notification from Klarna.

```
/**
 * Implements hook_form_alter().
 */
function mts_commerce_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'commerce_checkout_flow_multistep_default') {
    if (isset($form['payment_information'])) {
      hide($form['payment_information']);
      $customer_profile = Profile::create([
        'type' => 'customer',
        'uid' => \Drupal::currentUser()->id(),
        'address' => [
          'given_name' => '#',
          'family_name' => '#',
          'address_line1' => '#',
          'postal_code' => '12345',
          'locality' => '#',
          'country_code' => 'FI',
        ],
      ]);
      $customer_profile->save();
      $form['payment_information']['billing_information']['#default_value'] =  $customer_profile;
    }
  }
}
```

**Comment by cl83** [comment]
Thanks for the excellent explanation.

I still have a final issue with the push notification from klarna.

This is what i see in the logfiles. 
page not found | 08/29/2017 - 20:00 | /payment/notify/klarna_checkout?commerce_order=6&step… | Anonymous (not verified)

I tried to locate where in the code the routing url is defined but i couldn't find it.

**Comment by mitrpaka** [comment]
commerce_klarna_checkout uses default checkout return routes defined in commerce_payment (for offline payment gateways). Defined in buildTransaction() method under KlarnaManager.

```
    $create['merchant'] = [
      'id' => $plugin_configuration['merchant_id'],
      'terms_uri' => Url::fromUserInput($plugin_configuration['terms_path'], ['absolute' => TRUE])->toString(),
      'checkout_uri' => $this->getReturnUrl($order, 'commerce_payment.checkout.cancel'),
      'confirmation_uri' => $this->getReturnUrl($order, 'commerce_payment.checkout.return') . '&klarna_order_id={checkout.order.id}',
      'push_uri' => $this->getReturnUrl($order, 'commerce_payment.notify', 'complete') . '&klarna_order_id={checkout.order.id}',
      'back_to_store_uri' => $this->getReturnUrl($order, 'commerce_payment.checkout.cancel'),
    ];
```

**Comment by cl83** [comment]
Update: I found the problem.
I had named the payment gateway klarna and the return url was expecting that the payment gateway machine name was klarna_checkout. When renaming it to klarna checkout everything started working as expected.
